package UIModulo;

import ServerModule.AcessStatus;
import ServerModule.Report;
import ServerModule.User;
import xmlConvert.StringByte;
import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.xml.bind.JAXBException;
import xmlConvert.AcessStatusXml;
import xmlConvert.ConvertUser;
import xmlConvert.ReportXml;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SergioD
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        this.getContentPane().setBackground(Color.WHITE);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        jLabel1 = new javax.swing.JLabel();
        jTEmailCadastro = new javax.swing.JTextField();
        jBCadastrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jBEntrar = new javax.swing.JButton();
        jTEmailEntrar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jBParcial = new javax.swing.JButton();
        jBSair = new javax.swing.JButton();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Email");

        jBCadastrar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jBCadastrar.setText("Cadastrar-se");
        jBCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setText("Boca de Urna");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Cadastre-se");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Email");

        jBEntrar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jBEntrar.setText("Entrar");
        jBEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEntrarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Entrar");

        jBParcial.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBParcial.setText("Estatisticas");
        jBParcial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBParcialActionPerformed(evt);
            }
        });

        jBSair.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBSair.setText("Sair");
        jBSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBSair, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBCadastrar)
                    .addComponent(jTEmailCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jBEntrar)
                    .addComponent(jTEmailEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(37, 37, 37))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBParcial, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jBSair))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTEmailCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTEmailEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCadastrar)
                    .addComponent(jBEntrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jBParcial)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarActionPerformed
            if(jTEmailCadastro.getText().contains("@") && !jTEmailCadastro.getText().contains(" ") && jTEmailCadastro.getText().contains(".")){
        try {
            // TODO add your handling code here:
          
            Socket socket = new Socket("localhost", 10001);
            String emailCadastro = jTEmailCadastro.getText();
            
            byte b[] = null;
            User user = new User();
            user.setEmail(emailCadastro);
            
            String codigo = StringByte.convertByteString(ConvertUser.ObjXml(user), "CAD;");
            
            b = StringByte.convertStringByte(codigo);
            
            socket.getOutputStream().write(b);
            socket.getOutputStream().flush();
            
            InputStream input = socket.getInputStream();
            ByteArrayOutputStream temp = new ByteArrayOutputStream();
            byte[] msg = new byte[1];
            
            while(input.read(msg) != -1){
                temp.write(msg);
            }
        
            String mensagem = temp.toString();
            JOptionPane.showMessageDialog(null, mensagem);
            
        } catch (IOException | JAXBException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        }else{
            JOptionPane.showMessageDialog(null, "Email invalido!");
        }
        
            jTEmailCadastro.setText("");
    }//GEN-LAST:event_jBCadastrarActionPerformed

    private void jBEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEntrarActionPerformed
        try {
            Socket socket = new Socket("localhost", 10001);
            
            String emailEntrar = jTEmailEntrar.getText();
            
            byte b[] = null;
            User user = new User();
            user.setEmail(emailEntrar);
            
            String codigo = StringByte.convertByteString(ConvertUser.ObjXml(user), "LOG;");
            
            b = StringByte.convertStringByte(codigo);
            
            socket.getOutputStream().write(b);
            socket.getOutputStream().flush();
            
            InputStream input = socket.getInputStream();
            ByteArrayOutputStream temp = new ByteArrayOutputStream();
            byte[] msg = new byte[1024];

            input.read(msg);
            temp.write(msg);

            int aux = 0;
            for(int i = 0; i < msg.length; i++ ){
                if(msg[i] != 0){
                    aux++;
                }
            }
            
            temp.close();
            byte[] dad = new byte[aux];
            System.arraycopy(msg, 0, dad, 0, aux);
            
            ByteArrayOutputStream temp1 = new ByteArrayOutputStream();
            temp1.write(dad);
            
            if(dad.length > 25){
                   
               AcessStatus acess = (AcessStatus) AcessStatusXml.XmlObj(dad);
               
               if(acess.getStatus().equalsIgnoreCase("V")){
               
               Votacao votacao = new Votacao(acess);
               votacao.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
               votacao.setResizable(false);
               votacao.setLocationRelativeTo(null);
               votacao.setVisible(true);
               
               JOptionPane.showMessageDialog(null, "Eleitor Ja Votou!");
               }else{
                    Votacao votacao = new Votacao(acess);
                    votacao.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
                    votacao.setResizable(false);
                    votacao.setLocationRelativeTo(null);
                    votacao.setVisible(true);
               }
            }if(dad.length == 25){
                    
                String mensagem = temp1.toString();
                jTEmailEntrar.setText("");
                JOptionPane.showMessageDialog(null, mensagem);
            }
            
        } catch (IOException | JAXBException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBEntrarActionPerformed

    private void jBParcialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBParcialActionPerformed
        try {
            // TODO add your handling code here:

            Socket socket = new Socket("localhost", 10001);
            String codigo = "PAL;";
            
            byte dados[] = null;
            
            dados = StringByte.convertStringByte(codigo);
            socket.getOutputStream().write(dados);
            socket.getOutputStream().flush();
            
            InputStream in = socket.getInputStream();
            ByteArrayOutputStream temp = new ByteArrayOutputStream();
            byte[] b = new byte[1024];

            in.read(b);
            temp.write(b);

            int aux = 0;
            byte[] dad = null;
            
            for (int i = 0; i < b.length; i++) {
                if (b[i] != 0) {
                   aux++;
                }
            }

            temp.close();
            dad = new byte[aux];
            System.arraycopy(b, 0, dad, 0, aux);
            Report rip = ReportXml.XmlObj(dad);
            
            
            Apuracao apuracao = new Apuracao(rip);
            apuracao.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
            apuracao.setResizable(false);
            apuracao.setLocationRelativeTo(null);
            apuracao.setVisible(true);
            
        } catch (IOException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JAXBException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jBParcialActionPerformed

    private void jBSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jBSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Inicio inicio = new Inicio();
                inicio.setLocationRelativeTo(null);
                inicio.setResizable(false);
                inicio.setVisible(true);
                //new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCadastrar;
    private javax.swing.JButton jBEntrar;
    private javax.swing.JButton jBParcial;
    private javax.swing.JButton jBSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTEmailCadastro;
    private javax.swing.JTextField jTEmailEntrar;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    // End of variables declaration//GEN-END:variables
}
